/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./components/AppIcon.vue')['default']
    AppNavbar: typeof import('./components/AppNavbar.vue')['default']
    AppTabbar: typeof import('./components/AppTabbar.vue')['default']
    BookCover: typeof import('./components/BookCover.vue')['default']
    ListenMiniBar: typeof import('./components/ListenMiniBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShelfCategoryRail: typeof import('./components/ShelfCategoryRail.vue')['default']
    ThemePicker: typeof import('./components/ThemePicker.vue')['default']
    WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['default']
    WdCell: typeof import('@wot-ui/ui/components/wd-cell/wd-cell.vue')['default']
    WdCellGroup: typeof import('@wot-ui/ui/components/wd-cell-group/wd-cell-group.vue')['default']
    WdConfigProvider: typeof import('@wot-ui/ui/components/wd-config-provider/wd-config-provider.vue')['default']
    WdIcon: typeof import('@wot-ui/ui/components/wd-icon/wd-icon.vue')['default']
    WdInput: typeof import('@wot-ui/ui/components/wd-input/wd-input.vue')['default']
    WdLoading: typeof import('@wot-ui/ui/components/wd-loading/wd-loading.vue')['default']
    WdNavbar: typeof import('@wot-ui/ui/components/wd-navbar/wd-navbar.vue')['default']
    WdPopup: typeof import('@wot-ui/ui/components/wd-popup/wd-popup.vue')['default']
    WdSegmented: typeof import('@wot-ui/ui/components/wd-segmented/wd-segmented.vue')['default']
    WdTabbar: typeof import('@wot-ui/ui/components/wd-tabbar/wd-tabbar.vue')['default']
    WdTabbarItem: typeof import('@wot-ui/ui/components/wd-tabbar-item/wd-tabbar-item.vue')['default']
  }
}

// For TSX support
declare global {
  const AppIcon: typeof import('./components/AppIcon.vue')['default']
  const AppNavbar: typeof import('./components/AppNavbar.vue')['default']
  const AppTabbar: typeof import('./components/AppTabbar.vue')['default']
  const BookCover: typeof import('./components/BookCover.vue')['default']
  const ListenMiniBar: typeof import('./components/ListenMiniBar.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ShelfCategoryRail: typeof import('./components/ShelfCategoryRail.vue')['default']
  const ThemePicker: typeof import('./components/ThemePicker.vue')['default']
  const WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['default']
  const WdCell: typeof import('@wot-ui/ui/components/wd-cell/wd-cell.vue')['default']
  const WdCellGroup: typeof import('@wot-ui/ui/components/wd-cell-group/wd-cell-group.vue')['default']
  const WdConfigProvider: typeof import('@wot-ui/ui/components/wd-config-provider/wd-config-provider.vue')['default']
  const WdIcon: typeof import('@wot-ui/ui/components/wd-icon/wd-icon.vue')['default']
  const WdInput: typeof import('@wot-ui/ui/components/wd-input/wd-input.vue')['default']
  const WdLoading: typeof import('@wot-ui/ui/components/wd-loading/wd-loading.vue')['default']
  const WdNavbar: typeof import('@wot-ui/ui/components/wd-navbar/wd-navbar.vue')['default']
  const WdPopup: typeof import('@wot-ui/ui/components/wd-popup/wd-popup.vue')['default']
  const WdSegmented: typeof import('@wot-ui/ui/components/wd-segmented/wd-segmented.vue')['default']
  const WdTabbar: typeof import('@wot-ui/ui/components/wd-tabbar/wd-tabbar.vue')['default']
  const WdTabbarItem: typeof import('@wot-ui/ui/components/wd-tabbar-item/wd-tabbar-item.vue')['default']
}